"""empty message

Revision ID: 93965b5805d9
Revises: e23f3894a72d
Create Date: 2018-11-19 16:55:34.569152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93965b5805d9'
down_revision = 'e23f3894a72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'order')
    # ### end Alembic commands ###
